# Generated by Django 4.2.6 on 2023-10-27 07:04

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_img_alter_product_date_begin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slag', models.CharField(max_length=150, verbose_name='Slag')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('date_begin', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата создания')),
                ('activate', models.BooleanField(default=True)),
                ('count_views', models.IntegerField(verbose_name='Количество просмотров')),
            ],
        ),
    ]
