# Generated by Django 4.2.6 on 2023-10-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slag',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='count_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
